# Summer Internships for students

We can pay students a bursary (as ‘financial assistance’) rather than wages because:

1. The scheme is not internship or employment.

2. The scheme is an enhanced learning opportunity for students who have demonstrated a significant aptitude in subject areas.

3. The learning opportunity allows the student to practise in a live working environment whilst under supervision.

4. The student must produce written results either during or at the termination of the project.

5. The scheme takes place during the vacation period and the maximum attendance will be ten weeks.

6. The £200 weekly payment is as per guidance from the British Psychological Society and is to be paid as financial assistance to enable the student to remain in Plymouth to take part in the scheme.

The payments will be processed through P2P in Finance by completing Request for Payment forms (RFP) – see link below. Information required will be student name, number, bank details and reason for payment - to be presented as **Undergraduate Research Assistance Payment**. These payments will be made at the start and at the end of the scheme rather than weekly.

Important points for potential supervisors, to satisfy the above requirements:

* 1. Students should be paid in two lump sums
* 2. Supervisors and students should agree a set of learning outcomes before the placement begins, to be included in the report…
* 3. They should write a report on their work, to be read and commented on by the supervisor and sent to AHoS for Research at the end of the period of research.
* 4. The scheme is open to students at the end of stage 2, stage 3 if they have been on placement, and stage 4 if they are progressing to stage 5 on the MPsych programme. Students who have completed an undergraduate degree and are progressing straight onto a higher degree (MSc or full-time PhD), with only the academic summer holiday in between, also qualify.
* 5. All students should be made aware that this opportunity is potentially available. We will do this by advertising it as a possible outcome of successful research apprenticeships (JA action).

[Link to the RFP form to use](https://liveplymouthac.sharepoint.com/:x:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Payment%20Request%20Form.xlsx?d=w51c9a1805cbe4b5bb2dd1116001b907d&csf=1&web=1&e=5rrIS9)
Send to the School Office who will check it is correct before you send to payments.

Now if you want to pay someone for work, so with taxes etc. you will need to raise another type of contract, and then the person to contact about tax, etc is Rachel Edwards

**Compensation and Benefits (Payroll) Advisor**

Talent & Organisational Development|Plymouth University|17a Portland Villas|Drake Circus|Plymouth|PL4 8AA +44 (0)1752 588188 [rjedwards@plymouth.ac.uk](mailto:%7Crjedwards@plymouth.ac.uk)
