# Management 
[School](https://dle.plymouth.ac.uk/course/view.php?id=66067) - [Programme](https://dle.plymouth.ac.uk/course/view.php?id=38727) - [Gradbook](https://gradbook.plymouth.ac.uk/) - [RoomBooking](https://resourcebooker.plymouth.ac.uk/) - [Timetable](https://timetables.plymouth.ac.uk/) - [Panopto](https://plymouth.cloud.panopto.eu/) - 
[TechOffice](https://psy.plymouth.ac.uk) - 
[Primo](https://primo.plymouth.ac.uk) - 
[SONA](https://uopsop.sona-systems.com/)

-   [Workload Allocation Model](https://wam.psy.plymouth.ac.uk/admin/login/)
-   [Management Roles](https://wam.psy.plymouth.ac.uk/browse/admin-roles/) (who does what)
-   [Roles and Responsibilities](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Roles%20and%20responsibilites%20T%26L%20who%20does%20what%20Revised%20Oct%2018%20v3.docx?d=w8f5a5958b8524e1581adc245637cab6f&csf=1&web=1&e=CGJwTC)
-   [Calendar of School Meetings](https://outlook.office365.com/owa/calendar/54a64921ae844a78aa7ccd9d4b7badc2%40plymouth.ac.uk/04dad8c7933546e9b4f47531d64cca4f439343777348088576/calendar.ics) (ics format)
-   Give [Anonymous Feedback](https://www.psy.plymouth.ac.uk/communitybox/)
-   [How to deal with email](HowtodealwithEmail.png)
-   Weekly [Newsletter archive](https://us14.campaign-archive.com/home/?u=6d2359023df73cc9878607a99&id=91248e037a) and sign-up
-   [School GitHub site](https://github.com/PlymouthPsychology)
-   [School OneDrive folder](https://liveplymouthac.sharepoint.com/:f:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General?csf=1&web=1&e=XQtnWw)

## [Maps](https://liveplymouthac.sharepoint.com/:f:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Floorplan?csf=1&web=1&e=Ioh0bg) and Rooms

-   [PSQ Map](https://liveplymouthac.sharepoint.com/:b:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Floorplan/DLE%20copies/FindMyTutor.pdf?csf=1&web=1&e=SXJEAG) \| Link [1](https://www.psy.plymouth.ac.uk/home/Images/LINK1_DETAILED.png) \| [2](https://www.psy.plymouth.ac.uk/home/Images/LINK2_DETAILED.png) \| [3](https://www.psy.plymouth.ac.uk/home/Images/LINK3_DETAILED.png) \|[placement area map](https://liveplymouthac.sharepoint.com/:p:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Floorplan/Door%20Signs%20and%20Placement%20Area/placement%20area%20map.pptx?d=web2caf49ba314d83aa23045b1f051ced&csf=1&web=1&e=i0VgMH)
-   [Phone Directory](https://liveplymouthac.sharepoint.com/:u:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Floorplan/DLE%20copies/phonelist.html?csf=1&web=1&e=opgzkM)
-   [Editable Door Labels](https://liveplymouthac.sharepoint.com/:f:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Floorplan/Door%20Signs%20and%20Placement%20Area?csf=1&web=1&e=iNx0nM)
-   [Key Card Access](https://liveplymouthac.sharepoint.com/sites/u130/Lists/Key%20and%20Card%20Access/Item/editifs.aspx?List=eda6e8cf%2D3c8b%2D4b65%2D8245%2D52a7e673f992&ID=68&Source=https%3A%2F%2Fliveplymouthac%2Esharepoint%2Ecom%2Fsites%2Fu130%2FLists%2FKey%2520and%2520Card%2520Access%2FAllItems%2Easpx&Web=dfb318f4%2Db05c%2D427e%2Db810%2D297874959e12) form
-   [Psychology Room and Equipment Bookings](http://orb.plymouth.ac.uk/psy)

## Programme Management

-   [Programme Specifications](https://liveplymouthac.sharepoint.com/sites/u414/Programme%20Documentation/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fu414%2FProgramme%20Documentation%2FProgramme%20Specs&FolderCTID=0x012000214FFBAF16A46F4A831ED01387C65C43&View=%7BD65535BD%2D0623%2D48EB%2D9A60%2D48ACF47AB01E%7D) and [Module Records](https://liveplymouthac.sharepoint.com/sites/u414/Programme%20Documentation/Forms/AllItems.aspx?RootFolder=/sites/u414/Programme%20Documentation/Module%20Records&FolderCTID=0x012000214FFBAF16A46F4A831ED01387C65C43&View=%7bD65535BD-0623-48EB-9A60-48ACF47AB01E%7d)
-   [Student Voice System (module evaluation)](https://liveplymouthac.sharepoint.com/sites/u279/studentadministration/Student%20Voice/Forms/AllItems.aspx?viewpath=/sites/u279/studentadministration/Student%20Voice/Forms/AllItems.aspx)
-   Email M/M tutors: [Psy+HB](mailto:andrew.foey@plymouth.ac.uk), [Psy+Soc](mailto:J.M.Parsons@plymouth.ac.uk), [Psy+CCJS](mailto:chris.pacsoo@plymouth.ac.uk)
-   [PsySoc](https://www.upsu.com/societies/psysoc)
-   [Academic regulations](https://www.plymouth.ac.uk/student-life/your-studies/essential-information/regulations)
-   [Guide for Module Leaders\|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/FoB_Guide_for_Module_Leaders%5B1%5D.docx?d=w1753ead9a1c648529c0260943de07a24&csf=1&web=1&e=Lr3ZCq) (from FoB)

## Outside the School

-   [Essential University Links](https://liveplymouthac.sharepoint.com/UsefulLinks/SitePages/Home.aspx)

-   [Health & Safety](https://liveplymouthac.sharepoint.com/sites/u77/SitePages/Site%20Home.aspx) and [Incident Reporting Form](https://liveplymouthac.sharepoint.com/sites/X13/SitePages/Incident-Reporting.aspx)​

-   [Report Abuse - Bullying, Harassment, Racism](https://www.plymouth.ac.uk/student-life/services/student-services/speak-up)

-   Library[Psychology Support Guide](https://plymouth.libguides.com/psychology)

-   [Online Training](https://plymouth.learnupon.com/) and [GoodPractice](https://app.goodpractice.net/#/plymouth-uni/s/480f5100) 
* [Faculty of HHS Forms and templates](https://liveplymouthac.sharepoint.com/sites/officialdocumentcentre/Templates%20and%20forms) 
* [School Athena Swan site​](https://liveplymouthac.sharepoint.com/sites/u379) (committee only) 
* Faculty [Equality site](https://www.plymouth.ac.uk/about-us/university-structure/faculties/health/supporting-equality-within-the-faculty-of-health) and [Sharepoint](https://liveplymouthac.sharepoint.com/sites/u377/SitePages/FoH%20EDI%20Homepage.aspx) 

## [Human resources](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Site%20Home.aspx) (click for page)

-   [PDR](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Performance%20Development%20Review%20(PDR).aspx)

-   [Appointing people](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Recruitment.aspx)

-   [current vacancies](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Job%20Vacancies.aspx)

-   [Promotion](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Academic%20Promotions%20Career%20Pathways.aspx)

-   [Annual Leave and Public Holiday details](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Annual-Leave.aspx)

-   [Employee Self Service](https://hrservices.plymouth.ac.uk/tlive_ess/ess/#/) (Payslips, P60s!)

-   [Cyclescheme](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Cycle%20to%20Work%20Scheme.aspx?CT=1591086737955&OR=OWA-NT&CID=c49515e6-ed5a-42be-0835-986cbafb8a22) - get a tax free bike


## [IT Web pages](https://www.plymouth.ac.uk/about-us/university-structure/service-areas/it-services) (TIS)

-   phone support: 01752 588 588
-   [IT and Estates Support Portal](https://itselfservice.plymouth.ac.uk/)
-   [Work at home software](https://workathome.plymouth.ac.uk/)
-   [Edit your staff page on the Website](http://www.plymouth.ac.uk/admin)
-   [Digital Skills training](https://www.plymouth.ac.uk/services/digital-skills)

## Finance

-   [Key Travel](https://www.keytravel.com/uk/log-in) for Trains, Flights and Hotels
-   [How to submit an expenses claim](https://liveplymouthac.sharepoint.com/sites/u9/Training%20Page/Unit%204%20User%20Guide%20-%20How%20to%20Submit%20a%20Web%20Expense%20Claim.pdf#search=how%20to%20submit%20expense%20claims)
-   [Access Unit4](https://ubw.unit4cloud.com/uk_uop_prod_web/Default.aspx)
-   [Payment Request Form](https://liveplymouthac.sharepoint.com/:x:/r/sites/officialdocumentcentre/Templates%20and%20Forms/Payment%20Request%20Form.xlsx?d=w9ad9bbaa0fdd41a78e5985b2a298d4d9&csf=1&web=1&e=6PdAXU) (Excel Online)

## Printing and Photography

-   [DPC webpages](https://www.plymouth.ac.uk/about-us/university-structure/service-areas/marketing-and-communications/design-print-and-photography)
-   [University Image archive](https://plymouth.fotoware.cloud/fotoweb/archives/5000-Image-Library/?q=psychology) and [photoshoot form](https://www.plymouth.ac.uk/uploads/production/document/path/6/6839/photo_request_2016.pdf)
-   [School Image Archive](https://liveplymouthac-my.sharepoint.com/:f:/g/personal/jon_may_plymouth_ac_uk/EoKLfBdo2F9NvbkKLZeUBlsBdaa6wwL0HtspRf8sbCwhVQ?e=5pNPOp) and [Logo](https://liveplymouthac-my.sharepoint.com/:f:/r/personal/jon_may_plymouth_ac_uk/Documents/Plymouth/School%20Information%20Site/Logo?csf=1&web=1&e=RfJPQc)
-   [Printing Posters](https://www.plymouth.ac.uk/student-life/your-studies/library/library-printing-and-multimedia-services)
