# Leave and absence policies

- leave runs from 1 Aug each year
- you can carry 4 days over
- report sickness to the school office from the first day
- request leave via the school office who keep records of it 

## University documents/policies

All the relevant policies and guidance on leave are currently here:

https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Annual-Leave.aspx

Section 10 of the employment contract also has specifics:

https://liveplymouthac.sharepoint.com/sites/u114/HR%20portal%20documents/Contracts/Core_Terms_and_Conditions.pdf


## School leave and absence reporting procedure 

This leave and absence procedure is intended to ensure that all staff are able to make full use of their leave entitlement, and to work efficiently and flexibly off-campus, while maintaining effective delivery of teaching and administrative duties within their contracted time. It is intended to be read in conjunction with the [University’s core terms and conditions of work](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Employee%20Contracts,%20Terms%20and%20Conditions.aspx), and the [sickness absence reporting policies](https://intranet.plymouth.ac.uk/perdev/sicknessabsence/intranet.htm) 
 
### The key issues from these University policies that are relevant here are: 
 
* Academic staff are entitled to 35 days leave per year (pro rata for fractional contracts). Public holidays (eight days) are in addition to your leave entitlement, giving a total of 43 days leave, plus any period of University closure at Christmas.  
* Up to a maximum of 4 days leave may be carried forward each year. Any additional unused leave will be lost, unless exceptionally agreed by the Head of School.  
* Up to 6 weeks leave in a single block is allowable, outside of core teaching and assessment time.  
* The timing of leave is subject to the agreement of the Head of School / manager and is subject to the organisational requirements of the University.  
* Staff should give reasonable notice of holiday requests. Whilst every endeavour will be made to co-operate with staff in fixing the dates, agreement rests at the ultimate discretion of the University. 
* Wherever possible, detailed holiday schedules should be made as soon as reasonably practicable after the beginning of each academic year (August 1st). In determining holiday schemes, special regard will be given to lecturers with family responsibilities and those who wish to attend conferences or courses that are held in normal holiday periods. Conferences and courses will not count against holiday entitlement. 
* Staff have a responsibility to notify the University of all periods of absence through ill health, starting from the first day of absence.   
 
The purpose of having a School procedure is to ensure that we collectively have the necessary staff working to cover our key obligations in teaching (including the student experience), assessment, research and administration (including recruitment and marketing) as they arise through the year.  We also need to meet the requirements of the University as an employer, which has a duty of care towards its employees. With this aim in mind, we want a process that is reasonable and appropriate, and which does not create an unnecessary administrative burden.  
 
## School Procedure for Absence Reporting 
 
All periods of absence from the University during contracted hours (leave, working off campus, sickness) will be notified by using the appropriate online system or by contacting the School office, in advance in the case of leave and working off-campus.  
 
All periods of absence from the University during contracted hours will be explained in an out-of-office Outlook message that is consistent with the notification given to the office, and suitable for receipt by students, other University staff, and external recipients. The message should specify the period of absence wherever possible, and offer an alternate contact (e.g. for student enquiries).  
 
All periods of absence from the University during contracted hours should comply with relevant University policies.  
 
## Sickness absence 
 
The School should be notified of all periods of absence due to ill health, in line with University policy. This can be done by emailing or phoning the school office on your first day of sickness, by your normal start time. Staff should inform the office why you are away, how long you are likely to be off, and provide the details of any scheduled teaching or meetings that may need to be cancelled or rearranged. 
 
You will need to complete a self-certificate when you return to work to cover the first week of absence, and a statement of fitness work to work (fit note) from your GP when you absence is more than 7 consecutive days, including the weekend.  
 
## Annual leave 
* All academic staff should notify the School office of requests for periods of leave as soon as possible during the academic year, ideally shortly after the release of the final timetable for each semester.  
* Requests in line with University policy will be approved by the Head of School at the earliest opportunity, unless there is a compelling organisational reason to withhold approval. If approval is withheld, the Head of School will discuss the request with the staff member.  
* Periods of three or more day’s annual leave should be requested at least 2 weeks in advance. Periods of 1 day per week during the teaching and assessment period, and 2 days per week at other times, should be requested at least two working days in advance. 
* Where leave spans two academic years (July – August) it should be requested prior to the start of the leave in the earlier of the two years.  
* Periods of leave during teaching and assessment time are possible but may not be approved if they conflict with teaching, administrative or research commitments. Individuals wishing to apply to take leave during teaching and assessment time should discuss the case with the Head of School in the first instance.  
* Changes to previously agreed periods of leave will require re-approval as described above.  
 
 
## Working away from the University (including working at home).  
 
The School encourages flexible working practices and recognises the value of working off campus, at collaborating institutions, and at home, but does have a responsibility to staff, students and the University to know where staff are working at all times. For insurance purposes, all work conducted off campus needs to be recorded using the appropriate University systems.  
 
Requests for longer periods of working away from the university will normally be granted (e.g. a week spent marking exam scripts at home is likely to be approved) unless there are compelling organisational reasons to withhold approval.  
 
Staff planning to work away from the University for an extended period of time during contracted hours (i.e. more than 1 day in a week during teaching and assessment time, or more than 2 days in a week outside teaching and assessment time) should seek prior approval from the Head of School at least 2 weeks in advance of the absence.  The approval request should specify the period away, the nature and location of the work planned while away, and the steps taken to mitigate the effects of the planned period away.  
 
Staff planning to work away from the University for short periods during contracted hours (1 day a week during teaching and assessment time or 2 days a week outside teaching and assessment time) do not need prior approval, but are required to give prior notification to the School office. This notification should confirm that the absence will not negatively impact upon the working of the School.  
 
Because working away from the University constitutes work, you should provide contact details for your period of absence, and should respond to reasonable work requests, including responding to email requests within two working days, unless agreed in advance by the Head of School.  
 
 
## Part-time working (fractional contract) and non-contracted time 
 
The procedures above apply to working hours within your University contract. For those staff on fractional appointments (i.e. less than full-time) there is an additional requirement that the School is aware when people are working for the School, and when they are not. While the School is willing to adopt a flexible approach to the pattern of work at different times in the year, the organisational requirements of the School need to be met.  
 
The expectation will be that the fractional contract will apply equally to every working week, unless agreed in advance by the Head of School.  
 
Staff on fractional contracts wishing to constrain their working pattern (e.g. to specific days, or specific hours in the week), or wishing to distribute their workload differently across different parts of the year should seek the approval of the Head of School prior to the start of the Academic year in which it will apply, using the [University’s Flexible working procedure](https://documents.plymouth.ac.uk/uop/documents/Personnel%20and%20Development/Pay%20and%20hours%20of%20work/Flexible%20working%20procedure.doc)
 
Staff on fractional contracts without specific constraints should notify the School of the periods during the working week when they are working for the University, and the periods when they are not, at least 2 weeks in advance.
