# Quick Links to Modules

[School](https://dle.plymouth.ac.uk/course/view.php?id=66067) - [Programme](https://dle.plymouth.ac.uk/course/view.php?id=38727) - [Gradbook](https://gradbook.plymouth.ac.uk/) - [RoomBooking](https://resourcebooker.plymouth.ac.uk/) - [Timetable](https://timetables.plymouth.ac.uk/) - [Panopto](https://plymouth.cloud.panopto.eu/) - [SONA](https://uopsop.sona-systems.com/)

This section provides direct links to the 2024-25 DLE sites and S4 pages for all programmes and modules. It is organised by Programme, so also provides an overview of all teaching.

The [2023-24](https://discourse.psy.plymouth.ac.uk/t/quick-access-to-dle-and-s4-pages/1365), [2022-23](https://liveplymouthac.sharepoint.com/sites/u70/SitePages/DLE%20Quick%20Access%202022-23.aspx), [2021-22](https://liveplymouthac.sharepoint.com/sites/u70/SitePages/DLE%20Quick%20Access%202021-22.aspx) and [2020-21](https://liveplymouthac.sharepoint.com/sites/u70/SitePages/Psychology%20DLE%20sites%202020-21.aspx) sessions are still online. For earlier years, use the [DLE Site Home](https://dle.plymouth.ac.uk/?redirect=0) Search box - type module code and year e.g., 'PSYC204 18'

## [School of Psychology DLE](https://dle.plymouth.ac.uk/course/view.php?id=66067) (including office hours) {.unlisted .unnumbered}

## [Foundation Year](https://dle.plymouth.ac.uk/course/view.php?id=51939) (PL: Sophie Homer) {.unlisted .unnumbered}

**Semester 1:** [001 Foundations](https://dle.plymouth.ac.uk/local/permalink?id=PSYC001-24/AU/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3kAAA/view) (Sophie Homer) - [002 Everyday](https://dle.plymouth.ac.uk/local/permalink?id=PSYC002-24/AU/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3lAAA/view) (Sophie Homer)

**Semester 2:** [003 Health & Behaviour](https://dle.plymouth.ac.uk/local/permalink?id=PSYC003-24/SP/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3zAAA/view) (Andy Wills) - [005 Connecting Psychology](https://dle.plymouth.ac.uk/local/permalink?id=PSYC005-24/SP/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh0000018ChqIAE/view) (Zahra Hussain)

## [BSc/MPsych Psychology](https://dle.plymouth.ac.uk/course/view.php?id=38727) **PL: Peter Jones** {.unlisted .unnumbered}

*Stage 1 Semester 1* - [421 Cognitive](https://dle.plymouth.ac.uk/local/permalink?id=PSYC421-24/AU/M) Chris Berry [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh000000FWD2IAO/view) - [422 Clinical and Developmental](https://dle.plymouth.ac.uk/local/permalink?id=PSYC422-24/AU/SB/M) Ed Symes [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh000000FWD4IAO/view) - [423 Environmental](https://dle.plymouth.ac.uk/local/permalink?id=PSYC423-24/AU/M) Kayleigh Wyles [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh000000FWD3IAO/view)

*Stage 1 Semester 2* - [424 Social](https://dle.plymouth.ac.uk/local/permalink?id=PSYC424-24/SP/SU/M) Mila Mileva [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh000000FWD1IAO/view) - [425 Perception and Brain](https://dle.plymouth.ac.uk/local/permalink?id=PSYC425-24/SP/SB/M) Zahra Hussain [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh000000FWD5IAO/view) - [426 Motivation and Performance](https://dle.plymouth.ac.uk/local/permalink?id=PSYC426-24/SP/SU/M) Jon Rhodes [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh000000FWD0IAO/view)

*Stage 2 Semester 1* - [514 ID, Soc & Dev](https://dle.plymouth.ac.uk/local/permalink?id=PSYC514-24/AU/SB/M) Jaysan Charlesford [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnQAAQ/view) - [515 Health and Wellbeing](https://dle.plymouth.ac.uk/local/permalink?id=PSYC515-24/AU/SB/M) Julie Ji [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnOAAQ/view) - [519 RMiP1](https://dle.plymouth.ac.uk/local/permalink?id=PSYC519-24/AU/SB/M) and [Metasite](https://dle.plymouth.ac.uk/course/view.php?id=78854) Ben Whalley [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnRAAQ/view)

*Stage 2 Semester 2* - [513 Cognitive and Biological](https://dle.plymouth.ac.uk/local/permalink?id=PSYC513-24/SP/SB/M) Michael Verde [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnVAAQ/view) - [516 Applied Psychology](https://dle.plymouth.ac.uk/local/permalink?id=PSYC516-24/SP/SB/M) Steve Minton [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnTAAQ/view) - [520 RMiP2](https://dle.plymouth.ac.uk/local/permalink?id=PSYC520-24/SP/SB/M) and [shared-content site](https://dle.plymouth.ac.uk/local/permalink?id=PSYC520_X-24/SP/SB/M) Julien Besle [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnUAAQ/view)

*Stage 4* - [601 Options 1](https://dle.plymouth.ac.uk/local/permalink?id=PSYC601-24/AU/SB/M) Gustav Kuhn [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnaAAA/view) - [602 Options 2](https://dle.plymouth.ac.uk/local/permalink?id=PSYC602-24/AU/SB/M) Gustav Kuhn [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnYAAQ/view) - [603 Options 3](https://dle.plymouth.ac.uk/local/permalink?id=PSYC603-24/SP/SB/M) Jan Woike [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnncAAA/view) - [604 Options 4](https://dle.plymouth.ac.uk/local/permalink?id=PSYC604-24/SP/SB/M) Jan Woike [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnneAAA/view) - [605 Dissertation](https://dle.plymouth.ac.uk/local/permalink?id=PSYC605-24/AY/AU/M) Matt Roser [**S4-link**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnWAAQ/view)

## Minors student modules {.unlisted .unnumbered}

*Stage 1* - Semester 1 [PSYC419 Cognitive Psychology and Applied Psychological Research](https://dle.plymouth.ac.uk/local/permalink?id=PSYC419-24/AU/SB/M) - Chris Longmore [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go8fAAA/view) - Semester 2 [PSYC420 Social and Developmental Psychology](https://dle.plymouth.ac.uk/local/permalink?id=PSYC420-24/SP/SB/M) - Mila Mileva [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gqDpAAI/view) - Semester 2 [PSYC427 Health Behaviour](https://dle.plymouth.ac.uk/local/permalink?id=PSYC427-24/SP/SB/M) - Jon Rhodes [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh00000147K5IAI/view)

*Stage 2* - Semester 1 [PSYC521 Biological Basis of Behaviour](https://dle.plymouth.ac.uk/local/permalink?id=PSYC521-24/AU/SB/M) - Mathew Hudson [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnPAAQ/view) - Semester 2 [PSYC522 Individual Differences in Behaviour](https://dle.plymouth.ac.uk/local/permalink?id=PSYC522-24/SP/SB/M) - Jon May [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnSAAQ/view)

*Stage 4* - Semester 1 [PSYC608 Applied Topics in Psychology 1](https://dle.plymouth.ac.uk/local/permalink?id=PSYC608-24/AU/SB/M) - Matt Hudson [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnXAAQ/view) - Semester 2 [PSYC609 Applied Topics in Psychology 2](https://dle.plymouth.ac.uk/local/permalink?id=PSYC609-24/SP/SB/M) - Matt Hudson [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnndAAA/view)

## Zero Credit UG Modules {.unlisted .unnumbered}

[CPIE202 Careers and Placement planning](https://dle.plymouth.ac.uk/local/permalink?id=CPIE202-24/AY/AU/M) - Lindsay Marshall [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnMAAQ/view) [CPIE501 Placement Year](https://dle.plymouth.ac.uk/local/permalink?id=CPIE501-24/AY/AU/M) - Ed Symes [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnj0AAA/view) [PSYC600 Careers Planning](https://dle.plymouth.ac.uk/local/permalink?id=PSYC600-24/AY/AU/M) - Peter Jones [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnnNAAQ/view)

## [MSc Psychology (Conversion)](https://dle.plymouth.ac.uk/course/view.php?id=38758) (PL: Sonja Heintz) {.unlisted .unnumbered}

*Semester 1:* [704 ID/Soc/Dev](https://dle.plymouth.ac.uk/local/permalink?id=PSYC704-24/AU/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go45AAA/view) (Jaysan Charlesford) - taught with PSYC514 [705 Health & Wellbeing](https://dle.plymouth.ac.uk/local/permalink?id=PSYC705-24/AU/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go42AAA/view) (Julie Ji) - - taught with PSYC515 [719 RMIP1](https://dle.plymouth.ac.uk/local/permalink?id=PSYC719-24/AU/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go44AAA/view) - taught with PSYC519

*Semester 2:* [703 CogBio](https://dle.plymouth.ac.uk/local/permalink?id=PSYC703-24/SP/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3sAAA/view) (Michael Verde) - taught with PSYC513 [706 Options](https://dle.plymouth.ac.uk/local/permalink?id=PSYC706-24/SP/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3tAAA/view) (Jan Woike) - taught with PSYC603/4 [720 RMIP2](https://dle.plymouth.ac.uk/local/permalink?id=PSYC720-24/SP/SB/M) and [shared-content site](https://dle.plymouth.ac.uk/local/permalink?id=PSYC520_X-24/SP/SB/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3rAAA/view) (Julien Besle) - taught with PSYC520

*All year:* [707 Project](https://dle.plymouth.ac.uk/local/permalink?id=PSYC707-24/AY/PT/M)[**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3vAAA/view) (Sonja Heintz) [708 Careers](https://dle.plymouth.ac.uk/local/permalink?id=PSYC708-24/AY/AU/M)[**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3gAAA/view) (Sonja Heintz)

## MSc and MPsych Stage 5 {.unlisted .unnumbered}

[MPsych Advanced Psychology (stage 5) and MSc Research Methods in Psychology](https://dle.plymouth.ac.uk/course/view.php?id=72250) (Chris Berry) [MPsych Clinical Psychology](https://dle.plymouth.ac.uk/course/view.php?id=39019) and [MSc Clinical Psychology](https://dle.plymouth.ac.uk/course/view.php?id=72246) (Alison Bacon) [MPsych (stage 5) and MSc Human Neuroscience](https://dle.plymouth.ac.uk/course/view.php?id=72248) (Giorgio Ganis)

*Masters modules for these programmes are taken from these:* [721 Core Clin Competencies](https://dle.plymouth.ac.uk/local/permalink?id=PSYC721-24/SU/NS/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gqJEAAY/view) (Alyson Norman) [722 AP Project](https://dle.plymouth.ac.uk/local/permalink?id=PSYC722-24/AY/PT/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnixAAA/view) (Chris Berry) [723 Applied Clinical Research](https://dle.plymouth.ac.uk/local/permalink?id=PSYC723-24/AY/PT/M)[**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gniyAAA/view) (Nick Troop) [724 Neuroimaging and Neurostimulation](https://dle.plymouth.ac.uk/local/permalink?id=PSYC724-24/AY/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gniyAAA/view) (Giorgio Ganis) [725 Neuroscience Project](https://dle.plymouth.ac.uk/local/permalink?id=PSYC725-24/SP/PT/M)[**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnizAAA/view) (Matt Roser) [726 Foundations of Neuroimaging](https://dle.plymouth.ac.uk/local/permalink?id=PSYC726-24/AY/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnirAAA/view) (Nadège Bault)

[750 PDP](https://dle.plymouth.ac.uk/local/permalink?id=PSYC750-24/AY/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003go3mAAA/view) (Sean Fallon)

[760 Design and data fluency](https://dle.plymouth.ac.uk/local/permalink?id=PSYC760-24/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnivAAA/view) (Chris Mitchell) [761 Advanced data analysis](https://dle.plymouth.ac.uk/local/permalink?id=PSYC761-24/SP/SU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gqGLAAY/view) (Chris Mitchell) [762 Models of Intervention](https://dle.plymouth.ac.uk/local/permalink?id=PSYC762-24/AY/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnisAAA/view) (Sophie Homer) [763 Advanced Skills 1](https://dle.plymouth.ac.uk/local/permalink?id=PSYC763-24/AY/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnitAAA/view) (Jon May) [764 Advanced Skills 2](https://dle.plymouth.ac.uk/local/permalink?id=PSYC764-24/SP/SU/M)[**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gqEAAAY/view) (Chris Longmore) [765 Neuropsychology](https://dle.plymouth.ac.uk/local/permalink?id=PSYC765-24/SU/NS/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gqIwAAI/view) (Giorgio Ganis) [766 Practitioner Psychologist](https://dle.plymouth.ac.uk/local/permalink?id=PSYC766-24/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gniwAAA/view) (Deanna Gallichan)

## MSc Clinical Associate Psychologist (CAPS) PL: Peter Keohane {.unlisted .unnumbered}

[**S4**](https://plymuni.lightning.force.com/lightning/r/Programme_Cohort__c/a1e67000007WihYAAS/view) 


[PSYC7990](https://dle.plymouth.ac.uk/local/permalink?id=PSYC7990-24/AY/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnqpAAA/view) (Peter Keohane) - [PSYC7991](https://dle.plymouth.ac.uk/local/permalink?id=PSYC7991-24/AY/AUNS/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnqxAAA/view) (Alyson Norman) [PSYC7993](https://dle.plymouth.ac.uk/local/permalink?id=PSYC7993-24/AY/PT/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnqsAAA/view) (Helen Lloyd) [PSYC7995](https://dle.plymouth.ac.uk/local/permalink?id=PSYC7995-24/SP/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gqJDAAY/view) (Joanna Ede) [PSYC7996](https://dle.plymouth.ac.uk/local/permalink?id=PSYC7996-24/AY/AU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnqqAAA/view) (Josh Valoroso) [PSYC7997](https://dle.plymouth.ac.uk/local/permalink?id=PSYC7997-24/AY/SU/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a3867000003gnqvAAA/view) (Josh Valoroso) [PSYC7998](https://dle.plymouth.ac.uk/local/permalink?id=PSYC7998-24/AY/PT/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh0000019V8rIAE/view) (Helen Lloyd) [PSYC7999](https://dle.plymouth.ac.uk/local/permalink?id=PSYC7999-24/AY/PT/M) [**S4**](https://plymuni.lightning.force.com/lightning/r/Module_Cohort__c/a38Sh0000019V8sIAE/view) (Elise Dyer)

## [Doctorate in Clinical Psychology](https://dle.plymouth.ac.uk/course/view.php?id=4532) (4083) {.unlisted .unnumbered}

Year 1: [CPSYC620 Clinical Practice 1](https://dle.plymouth.ac.uk/local/permalink?id=CPSY620-24/AY/PT/M) - [CPSY621 Academic Competence 1](https://dle.plymouth.ac.uk/local/permalink?id=CPSY621-24/AY/PT/M) - [CPSY622 Research 1](https://dle.plymouth.ac.uk/local/permalink?id=CPSY622-24/AY/PT/M) Year 2: [CPSYC623 Clinical Practice 2](https://dle.plymouth.ac.uk/local/permalink?id=CPSY623-24/AY/PT/M) - [CPSY624 Academic Competence 2](https://dle.plymouth.ac.uk/local/permalink?id=CPSY624-24/AY/PT/M) - [CPSY625 Research 2](https://dle.plymouth.ac.uk/local/permalink?id=CPSY615-24/AY/PT/M) Year 3: [CPSYC626 Clinical Practice 3](https://dle.plymouth.ac.uk/local/permalink?id=CPSY626-24/AY/PT/M) - [CPSY627 Academic Competence 3](https://dle.plymouth.ac.uk/local/permalink?id=CPSY627-24/AY/PT/M) - [CPSY628 Research 3](https://dle.plymouth.ac.uk/local/permalink?id=CPSY628-24/AY/PT/M)
