# Teaching

[School](https://dle.plymouth.ac.uk/course/view.php?id=66067) - [Programme](https://dle.plymouth.ac.uk/course/view.php?id=38727) - [Gradbook](https://gradbook.plymouth.ac.uk/) - [RoomBooking](https://resourcebooker.plymouth.ac.uk/) - [Timetable](https://timetables.plymouth.ac.uk/) - [Panopto](https://plymouth.cloud.panopto.eu/) - 
[TechOffice](https://psy.plymouth.ac.uk) - 
[Primo](https://primo.plymouth.ac.uk) - 
[SONA](https://uopsop.sona-systems.com/)

## Lecturing and Workshops

-   [Overview of programmes and modules](#teaching-overview)
-   Uni [Teaching guidance](https://www.plymouth.ac.uk/about-us/teaching-and-learning/guidance-and-resources) and [Sharepoint](https://liveplymouthac.sharepoint.com/sites/x75/SitePages/Home.aspx) site
-   [Teaching Development Framework](https://liveplymouthac.sharepoint.com/sites/u411/SitePages/Teaching-Development-Framework-(TDF)-Resources.aspx?csf=1&web=1&e=vKar44&cid=bb75440b-27eb-4e5b-ba12-0962d69fce9a)
-   [Generic School Slide format](https://liveplymouthac.sharepoint.com/:p:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/Teaching/General%20information%20for%20staff/Teaching%20support%20resources/front%20slide%20template%20for%20lectures.pptx?web=1)
-   [Leganto](https://readinglists.plymouth.ac.uk/) (reading lists) and [Help Guide](https://plymouth.libguides.com/readinglists)
-   [Panopto Home](https://plymouth.cloud.panopto.eu/), [Info](https://dle.plymouth.ac.uk/course/view.php?id=26163) and [help - email](mailto:avrefreshandcapture@plymouth.ac.uk)
-   [Mentimeter](http://www.mentimeter.com/)
-   [Box of Broadcasts (BoB)](https://learningonscreen.ac.uk/ondemand)
-   [Risk Form for external speakers](https://plymouth.onlinesurveys.ac.uk/notification-of-external-speaker)
-   [Attendance recording](https://liveplymouthac.sharepoint.com/sites/u339/S4/SitePages/Attendance-Recording.aspx) and Check-in codes

## [PsyLab](http://www.psy.plymouth.ac.uk/psylab) and tutorials

-   [Tutorial groups](https://psy.plymouth.ac.uk/apps/tgw) (tile on PsyResources)
-   [Tutorial information for staff (2024-25)](#psylab-tutorials)
-   [Stage 1](https://dle.plymouth.ac.uk/mod/resource/view.php?id=768941) and [Stage 2](https://dle.plymouth.ac.uk/mod/resource/view.php?id=768942) schedule
-   [Room sizes\|attachment](upload://4NgXi4gmI0uffRbFbTe6AFuIseQ.docx) (60.1 KB) and [Room Booking](https://resourcebooker.plymouth.ac.uk/)

## Supporting Students

-   [Personal Tutoring](https://liveplymouthac.sharepoint.com/sites/u411/SitePages/Personal-Tutoring(1).aspx?csf=1&web=1&e=LqrpSK&cid=9ac5ea01-74e7-4911-8665-30732fdb8ae9) guide
-   [Teaching, supervision and support](https://liveplymouthac.sharepoint.com/sites/x75/SitePages/Home.aspx#academic-support)
-   [Reporting Bullying or Harassment](https://www.plymouth.ac.uk/forms/speak-up/report)
-   [Student Support Documents](https://www.plymouth.ac.uk/student-life/services/student-services/disability-and-dyslexia/student-support-documents-information-for-staff)
-   [Student Conduct resources](https://liveplymouthac.sharepoint.com/sites/u154/SitePages/Student%20Conduct.aspx)
-   [Extenuating Circumstances](https://liveplymouthac.sharepoint.com/sites/x70/SitePages/Extenuating-circumstances.aspx) webpages
-   [Online Ext Circs form](https://plymouthuniversity.formtitan.com/ECLTH#/)
-   [Careers Service](https://www.plymouth.ac.uk/student-life/your-studies/academic-services/careers-and-employability)
-   [Writing Café](https://www.plymouth.ac.uk/student-life/services/student-services/learning-development/writing-cafe)
-   [Overseas students](https://www.plymouth.ac.uk/student-life/services/international-students/international-student-advice)

## Assessment

-   [List of Psychology Assessments 2024-25](https://liveplymouthac-my.sharepoint.com/:x:/g/personal/jon_may_plymouth_ac_uk/ESiQf4yK3x1Dgmcv9JZmojMBkpSDfi1-R3cCcD4IYL806A?e=hQxs7k)
-   [UoP Examination Timetables](https://liveplymouthac.sharepoint.com/sites/x70/SitePages/Examination-timetables.aspx)
-   [School exam marking process](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/Teaching/General%20information%20for%20staff/Assessment%20Information/exam%20marking.docx?web=1)
-   [School marking and moderation procedures](https://liveplymouthac.sharepoint.com/:b:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Old%20SIS%20site/files/Marking-Moderation%20Stages%20and%20Responsibilities%20-%202023-24.pdf?web=1)
-   [Marking and Moderation - how it works (student-facing document)](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/Teaching/General%20information%20for%20staff/Assessment%20Information/Marking%20Moderation%20and%20feedback%20-%20how%20it%20works.docx?web=1)
-   [Marking and Feedback Guidelines using Turnitin Feedback Studio on the DLE](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/Teaching/General%20information%20for%20staff/Assessment%20Information/Marking%20using%20Turnitin.docx?web=1)
-   [Advice and guidance for staff when dealing with assessment offences.pdf\|attachment](https://liveplymouthac.sharepoint.com/:b:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/Teaching/General%20information%20for%20staff/Assessment%20Information/Advice%20and%20guidance%20for%20staff%20when%20dealing%20with%20assessment%20offences_2020.pdf?web=1)
-   Shiny apps for marking and moderation:
    -   [Combining a students marks on several assignments into a single mark](https://jonmay.shinyapps.io/CombineR/)
    -   [Statistical Moderation (single Q, many Markers)](http://jonmay.shinyapps.io/ModeratoR)
    -   [Compare Stage 4 options with other assessments](http://jonmay.shinyapps.io/Stage4OptionChecker)
    -   [Exam mark collator](https://jonmay.shinyapps.io/ExamineR/)
    -   [Evaluate effect of attendance on module mark](https://jonmay.shinyapps.io/AttendeR/)
-   [Releasing marks on DLE](https:///releasingmarks.html)
-   [PTT Marking teams site](https://teams.microsoft.com/l/team/19:14719d6ae5fd467982cb22af63c76598%40thread.skype/conversations?groupId=1771f4ac-3ad7-416d-a5ce-ae63d98f8d57&tenantId=5437e7eb-83fb-4d1a-bfd3-bb247e061bf1)
-   [Modified Assessment Provisions](https://www.plymouth.ac.uk/student-life/your-studies/essential-information/exams/help-and-support-for-exams/modified-assessment-provisions)
-   [UoP Assessment Resources](https://www.plymouth.ac.uk/about-us/teaching-and-learning/guidance-and-resources/assessment)
-   [Academic](https://www.plymouth.ac.uk/student-life/your-studies/essential-information/regulations) and [Exam](https://www.plymouth.ac.uk/student-life/your-studies/essential-information/exams/exam-rules-and-regulations) Regulations (UoP student-facing pages)

## Timetables

-   Official [Timetable](https://timetables.plymouth.ac.uk/), [Help](https://timetables.plymouth.ac.uk/help), [Intranet Site](https://liveplymouthac.sharepoint.com/sites/u72/SitePages/Site%20Home.aspx)
-   Unofficial [simplified timetables](https://dle.plymouth.ac.uk/mod/folder/view.php?id=1403819)
-   [24-25 University Weeks Calendar](https://liveplymouthac.sharepoint.com/:b:/s/u72/EX8TUUosbSBGrb5GsN9XszABtNNfMOEYncL3rDwY4lJAnQ) and [2025-26](https://liveplymouthac.sharepoint.com/:b:/r/sites/u72/Timetabling/University%20Calendars/25-26%20University%20Weeks%20Calendar.pdf) calendars
-   [Important dates](https://www.plymouth.ac.uk/student-life/academic-year-dates)
-   [Classlists for Stage 1 modules](https://classlists.plymouth.ac.uk/classlist.aspx?t=q&r=PSYC4)
-   [Classlists for Stage 2](https://classlists.plymouth.ac.uk/classlist.aspx?t=q&r=PSYC5)
-   [Classlists for Stage 4](https://classlists.plymouth.ac.uk/classlist.aspx?t=q&r=PSYC6)
-   [Classlists for Masters](https://classlists.plymouth.ac.uk/classlist.aspx?t=q&r=PSYC7)
-   [Timetable Change Request Form\|attachment](files/Timetable%20Change%20Request%20Form%20MAC%20Users.docx) (email to Michael Verde)
-   [Timetabling constraints and flexible working request forms.docx\|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Old%20SIS%20site/files/Timetabling%20constraints%20and%20flexible%20working%20request%20forms.docx?web=1)

## Placement Year and Year Abroad

-   [Overview web page](https://www.plymouth.ac.uk/schools/psychology/placement)
-   [Careers and Placements Staff.pptx\|attachment](https://liveplymouthac.sharepoint.com/:p:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Old%20SIS%20site/files/Careers%20and%20Placements%20Staff%20Induction.pptx?web=1)
-   email [placements team](mailto:placements@plymouth.ac.uk)
-   [Placement Monitoring](https://www.psy.plymouth.ac.uk/apps/placement)
-   [Year Abroad Scheme](https://www.plymouth.ac.uk/international/exchange-opportunities/outgoing-exchanges)

## Student projects

-   [Project Allocation System](http://www.psy.plymouth.ac.uk/apps/pas/) (both UG and MSc)
-   [Student Ethics Applications](https://www.psy.plymouth.ac.uk/apps/sop_ethics)
-   [Technical Specification form](http://www.psy.plymouth.ac.uk/home/Documents/TechnicalSpecification.docx)
-   [SONA Points system](https://uopsop.sona-systems.com/) and [Guidance](http://www.psy.plymouth.ac.uk/home/Documents/ParticipationResearchersGuide.pdf) and [app](http://www.sona-systems.com/app-download.aspx)
-   [SONA Paid system](https://uopsopp.sona-systems.com/)
-   [SWUC 2023](https://www.swuc2023.com) and [Plymouth Student Scientist](https://pearl.plymouth.ac.uk/handle/10026.1/12776) \## Central Data
-   [Student records (on S4)](https://plymuni.my.salesforce.com/)
-   [Guides on using S4](https://liveplymouthac.sharepoint.com/sites/u339/S4/User%20guides/Forms/AllItems.aspx)
-   [Module Records (DMRs) and Programme Specifications](https://liveplymouthac.sharepoint.com/sites/u414/Programme%20Documentation/Forms/AllItems.aspx)
