# Programmes
The School of Psychology offers the following programmes (the four digit programme codes are needed to find them on some older computer systems):

## Foundation Year
This is provided for applicants who do not have the prior qualifications necessary to enrol for the Undergraduate program. It consists of four modules, each lasting half a semester, scheduled one after the other. If all are passed, the student can progress to an Undergraduate program.

## Undergraduate

**BSc (Hons) Psychology** (0191) - this is the school's main programme, often referred to as '**single honours**'. Students take six 20 credit modules in each of three years (see below), with each year split into two Semesters (so three modules each semester). NB IN their final year, the Dissertation module is double-weighted, worth 40 credits, so there are only five modules.

The first two years are called **Stage 1** and **Stage 2**, and then Stage 3 is an optional work **placement year** between second year and the final year, which around a third of students opt to take. The final year is thus **Stage 4**. Stage 2 can also be studied abroad in the '**Year Abroad**' scheme.

In general, students must pass ALL modules in a stage to progress into the next stage. The pass mark is 40; if a module is failed then a referral attempt, capped at 40, is allowed in late August/early September (no more than three modules can be referred; students who fail more must repeat a stage). If one module is failed with a mark of 30-40, it can be treated as 'compensated' and the student can progress, but the mark is not altered. Exceptionally, one failed module can be 'trailed' and repeated during the following stage.

The programme has four modules each year which are required for BPS accreditation (known as **core**) and two which are not (known as **optional**, though they are not optional, and should not be confused with the Stage 4 'Options' modules).

There are three '**Majors**' programmes, where students take the 4 'core' modules from us and two from another school (so they do not take our optional modules):

* BSc (Hons) Psychology with Criminology and Criminal Justice Studies (3370)
* BSc (Hons) Psychology with Human Biology (0196)
* BSc (Hons) Psychology with Sociology (0202)

There is one **Minors** programme, BSc (Hons) Criminology and Criminal Justice Studies with Psychology, which does not belong to the school, where students take four modules in CCJS and two in Psychology. We used to offer these students the two optional modules, but now offer specific '**minors**' modules tailored specifically to them. Students from some other programmes also take these modules, particularly BSc Nutrition, Exercise and Health, and BSc Human Biosciences.

## Integrated Masters

Instead of graduating at the end of Stage 4, students can progress directly into an extra Masters year (Stage 5) to obtain an MPsych award:

* MPsych (Hons) Advanced Psychology (4661)
* MPsych (Hons) Clinical Psychology
* MPsych (Hons) Human Neuroscience 

These are identical in content to the stand-alone MSc courses below, and run until August. They are counted as an Undergraduate year by the SLC so do not require an additional loan and will not increase graduates eventual monthly repayments.

## Masters

We currently offer one-year Masters courses for Psychology graduates :

* MSc (Hons) Advanced Psychology
* MSc (Hons) Clinical Psychology
* MSc (Hons) Human Neuroscience

These three MSc courses are identical to stage 5 of the MPsych courses, but require a separate loan from the SLC so will increase graduates eventual monthly repayments.

In addition, we provide a **conversion course** for graduates from ther disciplines which qualifies them to join the BPS. It consists of Stage 2 modules with one Stage 4 module and a dissertation to be completed by August:

* MSc Psychology

## Summary
A student who enrols on the Foundation Year, progresses to an Undergraduate degree, does a placement year, and then transfers to an MPsych year, can be studying in the school for six years. They might then gain PhD funding, or work as a TARA for six years.
