# Induction Week for Students

Each academic year starts with an "induction week" during which each school organizes activities for both newly-enrolled and returning students at all stages. There are also University-wide activities during that week.

Staff at the School of Psychology may be involved in a few different ways

-   a restricted number of staff members prepare and give talks to students about what to expect from their respective stage of study for the coming years, including useful information to support them during the academic year. If you're one of these staff members, you will be contacted in due course (usually at the end of the previous academic year, in June).
-   All staff members who are personal tutors meet with their foundation, stage 1, stage 2 and, optionally, stage 4 tutees. Again, you will receive emails from the induction coordinator at the end of August regarding this. Foundation and stage 1 students will be invited to participate in a Treasure Hunt, the first clue of which is given to them by their tutor during this meeting.
-   There are a few community events to which all staff members are encouraged to participate
    -   Community coffee with stage 1 and stage 2 undergraduate students (usually on Wednesday at 1 pm in Link 301)
    -   Undergraduate Welcome Party (Usually at the Box on Wednesday or Thursday evening)

Here are some useful links regarding induction:

-   Link to the [full undergraduate Psychology 2024 induction schedule](https://liveplymouthac-my.sharepoint.com/:x:/g/personal/julien_besle_plymouth_ac_uk/EW8LGdYezPVKgHbeRiWmDQ8BiR4RB-BVBdRxn11FwaF5tg?e=eveTNK).
-   Information for both students and staff about undergraduate psychology induction activities is also available on the [undergraduate programme DLE](https://dle.plymouth.ac.uk/course/section.php?id=468345).

------------------------------------------------------------------------

And here is a typical email you might receive at the end of August as staff member if you have undergraduate tutees:

> Good morning all, In a couple of weeks time, on Monday 16th September 2024, Induction Week shall begin. Some members of staff contribute to the face-to-face dissemination of information in lecture theatres, and I have already sent out specific details to those individuals. However, all UG-facing academic staff in the School are involved in a number of activities during the week. Here is a summary of the induction week's activities. In bold are activities that you either should be available for (i.e. if you have UG tutees), or to which all staff are encouraged to attend:

> *Monday 16th September 2024*
>
> All day: Stage 1 and Foundation induction sessions (with select staff)
>
> *Tuesday 17th September 2024*
>
> All day: Stage 2 induction sessions (with select staff)
>
> *Wednesday 18th September 2024*
>
> 11:00: Meet your Stage 1 or foundation tutees and begin their treasure hunt **(all staff who have stage 1 or foundation tutees)**
>
> 12:00: Meet Stage 2 tutees **(all staff who have Stage 2 tutees)**
>
> 13:00: **Community Coffee** with stage 1 and 2 UG students, Link 301 **(all staff encouraged to attend)**
>
> 19:00: **UG welcome event** at The Box **(all staff encouraged to attend; free food, drinks and disco)**
>
> *Friday 20th September 2024*
>
> All day: Stage 4 induction sessions (with select staff)
>
> At about 15.00pm, Stage 4 students are asked to contact their tutor. You do not have to see them this day/time unless you want to, but should arrange a meeting with them soon. Feel free to email them in advance with your preferred arrangements.
>
> Naturally, some of these activities are a little less mandatory than others, but it will make a very positive difference to both the student community and the staff community if as many people as possible could engage with the social events, on Wednesday at 13.00 in Link 301 and then at The Box on Wednesday at 19.00.
