# Research
[School](https://dle.plymouth.ac.uk/course/view.php?id=66067) - [Programme](https://dle.plymouth.ac.uk/course/view.php?id=38727) - [Gradbook](https://gradbook.plymouth.ac.uk/) - [RoomBooking](https://resourcebooker.plymouth.ac.uk/) - [Timetable](https://timetables.plymouth.ac.uk/) - [Panopto](https://plymouth.cloud.panopto.eu/) - 
[TechOffice](https://psy.plymouth.ac.uk) - 
[Primo](https://primo.plymouth.ac.uk) - 
[SONA](https://uopsop.sona-systems.com/)

-   [Psychology Research website](http://www.plymouth.ac.uk/research/psychology)-   [School Seminars](http://www.plymouth.ac.uk/research/psychology/seminars) - on [DLE](https://dle.plymouth.ac.uk/course/view.php?id=66067&section=4)

## Getting Funding
-   [Je-S Research Council system ](https://je-s.rcuk.ac.uk/) - Now
    closed
-   [UKRI Funding Service](https://funding-service.ukri.org/signIn)
-   [Core questions for
    UKRI-FS](https://www.ukri.org/apply-for-funding/improving-your-funding-experience/how-applicants-use-the-ukri-funding-service/responsive-mode-opportunities-funding-service-core-application-section-questions-and-assessment/core-section-questions-and-how-they-will-be-assessed/#contents-list)
-   Resumé for Research and Innovation R4RI
    [template](https://www.ukri.org/publications/resume-for-research-and-innovation-r4ri-template/)
    and
    [Guidance](https://discourse.psy.plymouth.ac.uk/t/resume-for-researchers-r4ri-hints-and-tips/1398)
-   [Support for proposal writing
    ](https://www.plymouth.ac.uk/research/support/funding)
-   [Grant application flowchart
    ](https://www.plymouth.ac.uk/research/support/funding/research-funding-flowchart)
-   [10 Key Sentences
    ](http://www.parkerderrington.com/key-sentence-skeletons/), [How
    to win a
    grant](https://corticalia.wordpress.com/2015/09/01/how-to-write-a-winning-grant-proposal/)
-   How to write a [strong NIHR proposal
    ](https://www.nihr.ac.uk/researchers/apply-for-funding/how-to-apply-for-project-funding/make-a-strong-application.htm)
-   [Applying to
    ESRC](https://liveplymouthac.sharepoint.com/:p:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Applying%20to%20ESRC%20(2009).ppt?d=w4f7c47e161be4556899607c45b1bf45e&csf=1&web=1&e=2D4CPy)
-   [ESRC review
    process](https://liveplymouthac.sharepoint.com/:b:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/Research/Getting%20funding/ESRC%20Grant%20Assessment%20Process.pdf?web=1)
-   [Support available in
    School](https://liveplymouthac.sharepoint.com/:b:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Old%20SIS%20site/files/Research%20support%20and%20processes%20in%20psychology.pdf?web=1)
-   [Successful Application Library
    ](https://www.plymouth.ac.uk/research/support/funding/guidance)
-   [BRIC MRI proof-of-concept
    form](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/BRIC%20Proof%20of%20concept%20form.docx?d=w2a21fff8032e4818807e9146d3f11d1e&csf=1&web=1&e=Wk4xoE)
-   [Risk assessment
    ](https://liveplymouthac.sharepoint.com/sites/u77/DRAFT%20Health%20%20Safety%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fu77%2FDRAFT%20Health%20%20Safety%20Documents%2FRisk%20Management)
-   [Data Management Plans
    ](https://plymouth.libguides.com/researchdatamanagement/dmp)

To access Award Manager, log in to Unit4 via [Corporate Self
Service](https://liveplymouthac.sharepoint.com/UsefulLinks/SitePages/Corporate%20self-service%20and%20information.aspx)
then select ‘Award Management’ from the options on the left hand side.
If it is not there contact the [Funding Advisory
Service](mailto:fundingadvisoryservice@plymouth.ac.uk). **Watch this
[short
video](https://drive.google.com/file/d/1rV9yKYq9pTU-z9FtP9znx89O_uu4pVg3/view?usp=drive_web)
to understand how it works.**

## Doing Research

-   [Ethical
    review](https://www.plymouth.ac.uk/research/governance/ethical-review),
    [Application
    Process](https://liveplymouthac.sharepoint.com/sites/u136/SitePages/Staff%20and%20PhD%20Ethics%20Applications.aspx),
    [Online System](https://apply-ethicsonlinesystem.plymouth.ac.uk/)
-   [OpenSesame](https://osdoc.cogsci.nl/4.0/download/),
    [tutorials](https://osdoc.cogsci.nl/4.0/tutorials/beginner/) and
    [JATOS](http://jatos.plymouth.ac.uk/)server
-   [JISC Online surveys version
    3](https://app.onlinesurveys.jisc.ac.uk/login) and older [version
    2](https://admin.onlinesurveys.ac.uk/accounts/login/)
-   School [Limesurvey](https://psysurvey.plymouth.ac.uk/) server
    (called psysurvey) and [Guide on
    use](https://jon-may.github.io/limesurvey/docs/index.html)
-   [Prolific login](https://app.prolific.co/register/researcher)
-   email [Pointsadmin](mailto:sonaadmin.psy@plymouth.ac.uk) and access
    [points SONA](https://uopsop.sona-systems.com/) or [paid
    SONA](https://uopsopp.sona-systems.com/)
-   [Primo](https://primo.plymouth.ac.uk/),
    [Scopus](https://plymouth.idm.oclc.org/login?url=http://www.scopus.com)
    and [Web of Science](http://plymouth.libguides.com/webofscience)
-   [Intellectual Property and Data
    Ownership](https://www.plymouth.ac.uk/research/support/intellectual-property)

### Impact

-   [Ways of getting involved with
    NICE.docx\|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Ways%20of%20getting%20involved%20with%20NICE.docx?d=wd88d6d5ba05b471c9c2add2446ddd631&csf=1&web=1&e=uX4uB2)

-   Embedding impact in grant applications [Impact in grants -
    notes.docx\|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/Research/Generating%20impact/Impact%20in%20grants%20-%20notes%20from%2015%20Jul%202024.docx?web=1) [Impact in grants - Slides 15 Jul
    24.pdf\|attachment](https://liveplymouthac.sharepoint.com/:b:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/Research/Generating%20impact/Impact%20in%20grants%20-%20Slides%2015%20Jul%2024.pdf?web=1)

-   [Impact: What
    counts?](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Impact%20report%20Feb%202024.docx?d=w188971ce41d64832828b5021d92b7497&csf=1&web=1&e=9desGV) -
    Panopto of talk by Jackie Andrade, 23/2/2022

-   Using social media smartly: [Social Media Cheat Sheets for Academic
    Engagement.docx\|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Social%20Media%20Cheat%20Sheets%20for%20Academic%20Engagement.docx?d=wab31ed0e224449f1b2b9c88dc5243ee0&csf=1&web=1&e=hy7pc8) [Maximising impact through social
    media.docx\|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Maximising%20impact%20through%20social%20media.docx?d=w09e6c8d135314ee89c9a24c3d1f1c60b&csf=1&web=1&e=rApMTz)
    (17.2 KB) [Social media Content Guide -
    Research.pptx\|attachment](https://liveplymouthac.sharepoint.com/:p:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Social%20media%20Content%20Guide%20-%20Research.pptx?d=w294b9ce8954b44a489cdc5da1b256d4e&csf=1&web=1&e=Bz5OaX)
    (3.3 MB) How to write a blog [Research impact group Apr
    19th.docx\|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Research%20impact%20group%20Apr%2019th.docx?d=wf9cf9749fab942179039846bdfa56ebf&csf=1&web=1&e=QACSew)
    (16.5 KB)

-   Testimonials are useful impact evidence, showing how 'hard' evidence
    of impact (health improvement data, sales figures etc) links to your
    research. Here's guidance on how to collect
    [testimonials](https://www.fasttrackimpact.com/post/2018/02/23/getting-testimonials-to-corroborate-the-impact-of-your-research).

-   [Fast Track Impact](https://www.fasttrackimpact.com): everything you
    wanted to know about research impact and how to achieve it

-   [People in Research](https://www.peopleinresearch.org) An NIHR
    website supporting patient and public involvement (PPI) in research

-   SoP impact report: [Impact report Feb
    2024.docx\|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/Impact%20report%20Feb%202024.docx?d=w188971ce41d64832828b5021d92b7497&csf=1&web=1&e=icewNc)
    (89.8 KB)

-   SoP impact strategy: [staff meeting impact slides feb
    2024.pptx\|attachment](https://liveplymouthac.sharepoint.com/:p:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/staff%20meeting%20impact%20slides%20feb%202024.pptx?d=w065d8034a7bc4dc68aed123c4af56c01&csf=1&web=1&e=ofWejp)
    (1.8 MB)

-   [Video summaries of REF2021 impact case studies from Faculty of
    Health including
    Psychology](https://www.plymouth.ac.uk/research/ref2021/health)


### Open Science

-   [Open Science
    Blog](http://blogs.plymouth.ac.uk/research/2018/06/01/research-data-policy-2018-removing-the-barriers-to-open-data/),
    [Data
    Policy](https://www.plymouth.ac.uk/uploads/production/document/path/6/6913/Research_Data_Policy.pdf),
    [School Open Science Policy](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/School%20of%20Psychology%20open%20science%20strategy.docx?d=wde702b35891a4314a09af6ecfa08caee&csf=1&web=1&e=N466Y0)
-   [How to do open
    science](https://opennessinitiative.org/guidelines-for-authors/)
-   [Open publishing](https://plymouth.libguides.com/research/oa) :
    Library Info
-   [Read &
    Publish](https://plymouth.libguides.com/research/readandpublish)
    open access with no fees
-   [Very Brief Guide to R](https://ajwills72.github.io/rminr/#vbgtr)
-   [Zenodo.org](https://zenodo.org/) and [Open Science
    Framework](https://osf.io/)
-   Learning R: [RMinR](https://ajwills72.github.io/rminr/) (Stage 1)
    and [RMInP](https://benwhalley.github.io/rmip/) (Stage 2)
-   [R-Studio Server](https://rstudio.plymouth.ac.uk/)

### On acceptance

-   Add a record to [Pure](https://pure.plymouth.ac.uk/) and
-   Upload your [authors' copy of
    ms](https://liveplymouthac.sharepoint.com/sites/x103/SitePages/Deposit-your-Outputs.aspx)

## Postgraduate Students

-   [Doctoral College](https://www.plymouth.ac.uk/doctoralcollege)
-   [PhD Competition
    Criteria](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/SoP%20PGR%20Competition%20Scoring%20Criteria.docx?d=wba5a6cf324b5438dbe4b9893bd1919bd&csf=1&web=1&e=3z7dIe)
-   [Training for
    supervisors](https://www.plymouth.ac.uk/student-life/your-studies/research-degrees/examiners-chairs-and-supervisors/supervisors)
    and
    [examiners](https://www.plymouth.ac.uk/student-life/your-studies/research-degrees/examiners-chairs-and-supervisors/examiners-and-chairs)
-   [Gradbook](https://gradbook.plymouth.ac.uk/)
-   [Research Degrees
    Handbook](https://www.plymouth.ac.uk/student-life/your-studies/research-degrees/doctoral-college/research-degrees-handbook)
-   [Research Degrees Staff
    Manua](https://liveplymouthac.sharepoint.com/sites/x75/SitePages/PGR-Staff-Resources.aspx#staff-code-of-practice)l
-   [SWDTP pages](https://www.swdtp.ac.uk/)
-   School [PhD
    advert](https://www.plymouth.ac.uk/schools/psychology/phd-studentships)
    and
    [application](https://www.plymouth.ac.uk/student-life/your-studies/research-degrees/applicants-and-enquirers)page
-   [list of potential internal
    examiners](https://liveplymouthac-my.sharepoint.com/:x:/g/personal/patricia_kanngiesser_plymouth_ac_uk/EU0NlrgP5KNHg3KRT4dNxlsBZ3ZHZTdaIoEP28V7k6f7GA)
    with data for Gradbook

## Projects and Groups

-   [BRIC
    website](https://www.plymouth.ac.uk/research/psychology/brain-research-and-imaging-centre)
    and
    [Wiki-handbook](https://brichandbook.readthedocs.io/en/latest/index.html)
-   [School Research
    Site​​](http://www.plymouth.ac.uk/research/psychology)
-   [List of research
    Groups](https://liveplymouthac.sharepoint.com/:x:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/Research/List%20of%20research%20groups%201.xlsx?d=w778715c8726649e8a3dce0076ceeef70&csf=1&web=1&e=fP2wWP)
    and [When groups
    meet](https://liveplymouthac.sharepoint.com/:x:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/when%20research%20groups%20meet.xlsx?d=w1d88df429cf54556aea0e9ead8b4ddb9&csf=1&web=1&e=h1w9uc)
-   [Functional Imagery
    Training](https://www.plymouth.ac.uk/research/psychology/applied-psychology/functional-imagery-training)
-   [In the Dancer's Mind](http://blogs.plymouth.ac.uk/dancersmind/)​​
-   [Health Lab
    guides](https://liveplymouthac.sharepoint.com/:f:/s/u325/EjVG6rP9w9tOpfFe5P2zGWsBZ00q0tQ2rXULJy-txxoQww?e=rFl5Wc)
