# Research Information 

This section provides a quick overview of the systems in place to support the research activities of Academic Staff in the School of Psychology. It contains references to the links on the main post, but no actual links. It is structured to match the main page.

## School Seminars

There is normally a research seminar every Wednesday afternoon in teaching weeks, to which all staff and students are invited, with tea/coffee/biscuits beforehand. The Seminar Organisor* will periodically ask for suggestions about people to invite, and this is a good way to get a colleague elsewhere to visit so you can discuss research ideas or other collborations. The School will pay for their travel and overnight accommodation, and also an evening meal (for two staff and the speaker).

* To find out who is currently in a management role such as Seminar Organiser or AHoS-Research, consult the Management Roles link.

## Funding

The majority of Academic Contracts in the School include Research and the School is keen that everyone should be in a position to obtain external research funding. The Associate Head of School for Research (AHoS-Research)* is responsible for helping you to achieve this, and it will be discussed at your annual Performance and Development Review (PDR) meeting.

The UK Research Councils use a common submission portal, **Je-S,** but **Funder Information** provides links to their main sites. Note that Je-S is soon to be replaced by a new system.

The University has a team to provide **Support for Proposal Writing**, with a **Grant application flowchart** to help you through the process, and there are several links here on strategies to improve the chanes for your proposal, as well as a summary of the **Support available in School.** The Research office host a page whjioch includes access to a **successful applications library**, which is very useful for working out how to best write your proposal.

Not all research requires a large amount of external funding, and often pilot work needs to be done to make applications more likely to succeed. You can ask the School for small amounts of funding to conduct studies, provided that you can give a brief 'business case'. Depending upon the state of finances, there may be emails about 'Pump Priming' schemes or similar from the AHoS-R, with deadlines, or you may be able to apply at any time. It is best to just ask. With the opening of BRIC, some funding is available for **proof-of-concept** studies using the MRI scanner.

The **Award Manager** system within Unit4 should be used throughout the proposal writing, costing, reviewing, approval and submission process, and then once you get your grant to manage the project. You need to contact Funding Advisory to get access to this system, and it then appears in the left hand menu when you access Business World through Corporate Self-Service.

Once you have won funding, you will be supported by the Finance Office. Your project will be given a *'* *Work Order* **'** code that you will need to quote to get anything bought for you. The code will be two letters and six digits, e.g., RR105183, and may be followed by budget line codes of a dash and three digits e.g., '-101'. Finance will provide you with summaries of the costs and budgets regularly, but also on request. There is no facility for you to manage the budgets yourself, or to inspect them online. Be aware that costs (especially staff costs) often take several weeks to make it through their systems, so the information you receive reflects some time in the past rather than a current snapshot. Do check the costs carefully as mistakes do happen. **You cannot buy anything** yourself and expect to be reimbused, except for food and accommodation. Ask the School Office or Tech Office to make small purchases online using the School Credit Card, but larger purchases may require authorisation, especially computing equipment. Travel and Accommodation should be booked through Key Travel (see Financial Stuff in Management). When you use KeyTravel, you provide the Word Order code to charge things directly to your project. After your trip, subsistence costs can be reimbursed by making an *Expense Claim* using Unit4, which you will definitely need help to do the first few times. Keep all receipts, scan them, and then upload the scans to Unit4 (beware of file size limits). See the nit4 section at the end of the Management column.

Projects that pay for staff time generate a surplus for the University, some of which is returned to the School Budget, and which can be made available for you to spend via a *Strategic Research Account (SRA)* **.** Any money allotted must be spent by the end of the financial year (July 30th). The balance will remain in your SRA, but the school will no longer have it, so it is illusory. Getting money put into your SRA is not automatic, and you cannot easily tell what is in your SRA other then by using Unit4. Ask the AHoS-Research for help when you get into this position.

## Doing Research

Before collecting any research data, whether or not you expect it to be published, you need to obtain **ethical approval**. For Staff and Postgraduates, there is an **Online System** to complete which will send your application to the Faculty Ethical Committee. It can take several weeks for scrutiny and changes are often requested, so apply in good time. Note that for any research conducted away from the University, a letter from the host organisation giving permission is required.

The open platform **OpenSesame** has been adopted to support computer based experimentation, and the school has a **JATOS** server to run experiments online (ask Tech Office for an account). For online surveys, the school currently has a paid-for **Qualtrics** aaccount and there is an active user group for it, although future funding is not certain. You can obtain a login from **PsyResources**. Some staff might have *SurveyMonkey* accounts funded by research grants and if you ask around they may share access. The University prefers **JISC-Online Surveys** and you can obtain an account from the IT Support Portal (aka TIS).

To recruit general public for online studies, we have a **Prolific** account, but funding is required (can be applied for within the school).

We use the **SONA Participation** system to run paid and 'course-credit' research within the school. All stage 1 and stage 2 undergraduates have to take part in 11 hours of research participation (15 mins = 0.5 points, 30 mins=1 point or £5, etc), and stage 4 use the points they collect in stage 2 to recruit other students for their dissertations. MSc students are given 40 points; PhD students and Staff can ask for 100 points at the start of each academic year, and further points will be distributed in Semester 2. Points have to be collected/used by a date near the end of Semester 2, so plan your research accordingly. SONA is run by the **pointsadmin** technical officer. You will get emails from pointsadmin when points are available to ask for, but if you have an urgent need, ask anyway.

Paid studies can also be run using SONA, provided you have funds, and participants can receive Amazon Vouchers automatically at a rate of £5 per half hour (minimum £5). To pay people cash or using vouchers, some form filling is required - do not use your own money and attempt to claim it back. We currently have a systen in place to provide digital **Amazon vouchers**, but older forms are available in **Getting Money to pay Participants,** along with cost approval forms for postgraduate studies. Participants receiving benefits shoukld be given a vesion of the **Letter for participants receiving benefits** to show to the JobCentre.

You can get Undergraduates to help run your research in four ways: by signing them up each Easter as next year's Stage 4 or Stage 5 *Dissertation Students*; by taking them on as *Research Apprentices*; by recruiting them as an *Internal Placement Student*; or by employing them for a few weeks during the summer vacation on an *Internship*. Apprentices can be recruited for half a day a week for ten weeks (nominally, this is flexible) by placing an **advert** and then **registering** them. They are usually Stage 1 or 2 students who volunteer in exchange for an insight into research techniques before doing their project, but some Stage 4 or 5 students also volunteer to broaden their experience. You can ask for extra Participation Points as an incentive to take them on (but they do not get any other resoucres). **Summer Employment** can be done through the research assisstance scheme and they can earn £200 for up to ten weeks. Details should be given to you by email towards the end of Semester 2. Placement Students take a whole year out of their course to do work experience with you and are a more serious commitment. You will be treated like an external palcement host. You must advertise, interview, and appoint via the placement office, between January and Easter. The placement runs for 36 weeks between September and June. Places are limited so liaise with the School's Internal Placements Tutor.

The Library collection and online journals is accessible through **Primo** (and should be , so our access is recorded and journals seen as highly used). We have access to the **Scopus** and **Web of Science** databases. As people did not use Primo, we no longer have subscriber access to APA journals, so you will have to scour Google Scholar for illicitly uploaded PDFs.

### Open Science

The School is committed to **Open Science**, and encourages all research to be preregistered, with materials, data and analysis scripts posted online in a persistent repository. The Univeristy maintains an **Open Science Blog,** and a **Data Policy**, and there is also a **School Policy**. There is a guide on **how to do open science**, and links to the **Zenodo.org** and **Open Science Framework**repositories for sharing plans and data.The Doctoral College have provided a very good **Guide to Data Management** (a plan is required for ethical approval)

The School uses **R for statistical analysis,** and support materials are provided, but *SPSS* is also available on managed computers and for download from the IT Work-at-home site (although provision of annual licence updates is routinely late and apparently confidential).

## On publication

For the REF we must make all papers accessible online within a short period following acceptance (not publication). There are two steps to follow:
1) add a record to **Symplectic Elements** so that the University knows about your publication and it appears on your staff web page (see entry at end of Management column).
2) Upload a PDF 'authors' copy' of your manuscript to the **University repository PEARL**.

Once a paper is published, Symplectic Elements will find it and either automatically update your manual record with the pubication details, or leave it in a Pending folder for you to 'Claim' as yours. It may also find others by similarly named authors who are not you, which you can Reject. If you have followed the guidelines and already created a manual record on acceptance, then you can merge the record of the published paper with your earlier manual one.

## REF Information

Our REF submission is in Unit of Assessment 4 (Psychology, Psychiatry and Neuroscience). The School's REF co-ordinator* will regularly ask you to rate your own papers, and to select a subset of these for consideration for the School's submission. You may be asked to read and rate colleagues' papers. It is in all of our interests to publish as many papers as we can that might be seen by REF Panels as 4-star; 3-stars are also useful, nothing else is useful for REF.

Impact Case Studies are also important and although we can only subit a few of these, they take years to build up and must be well evidenced and documented. It is worth collecting all potential evidence from non-HE users of your research just in case you need it in several years time. The University system for doing this is **VW Impact Tracker**, which you can use to capture all sorts of evidence file types. If your research does make an impact, and you are asked to prepare a case study, you will need this information then.

## Doctoral College

If you have an MPhil or PhD student, then they will be a member of the **Doctoral College**, who are responsible for administering all research postgraduates.

PhD students have a *Director of Studies* (DoS, their main supervisor) and a Supervisory Team of at least one other academic, who does not have to be in the School. You have to attend **training for supervisors and examiners** before you can supervise a student or be internal examiner for a thesis - everyone is expected to take this training shortly after appointment. Only people who have examined at least two vivas at Plymouth can be an internal examiner without also needing a Chair, so we have a **s** **preadsheet of examining experience** to record it.

**Gradbook** is an online system run by the Doctoral College where you access and record information about your research students. The Doctoral College require you to log regular meetings with your students using Gradbook, and to sign off formal progression through the programme including:

* RDC.1 (Project Plan) after 6 months (Full Time) or 12 months (Part Time)

* RDC.2 (Confirmation of Route to transfer from MPhil to PhD) before 18 months (FT) or 24 months (PT).

* RDC.3 (Examination Arrangements - appointment of examiners), at least four months before submision.

The RDC.1 and RDC.2 need to be reviewed by an Expert Commentator (another academic from within the school). You can choose who, in liaison with the PG Tutor. We usually expect the Expert Commentator to be appointed as Internal Examiner, as they will be familiar with the student's work. Other schools expressly forbid it.

The viva also needs an *External Examiner* **,** and these need to be approved by a committee, hence the need to complete RDC.3 in good time. The rules about who can be an external are in the **Research Degrees Handbook**. If the Externals has not previously externalled the viva will need a Chair (usually the PG Tutor), as will students who are employed by the University as research staff, who will need to have two Externals and a Chair.

Funding for PhD students is highly competitive but these are the main routes:
1) TARAs - the school employs several *Teaching and Research Associates* (TARAs) on five year 0.7FTE contracts to support workshops and marking and these are required to register for a Part Time PhD with fees waived. There are usually two vacancies a year for these posts.
2) SWDTP - as a member of the ESRC funded **South West Doctoral Training Partnership**, we can apply for full 3-year ESRC studentships. We have a good record of obtaining one a year through this scheme.
3) School/Faculty/University Studentships - depending upon the financial climate, the School tries to offer full-time studentships on terms equivalent to research council studentships each year. The Faculty and the University may also offer such schemes, and you will be emailed about these. We have a standing list of projects on an externally visible **School Phd Advert** web page. You can add your own project here by emailing the PG Tutor.
4) Overseas state funded studetns - you may receive a direct email from an overseas student who says they have funding. Do not just bin these, reply politely and foward them to the PG Tutor, who will do some quality control and then circulate them if they are plausible. When you see one circulated, please do consider whether you could offer the student supervision. We have had several strong students in the past.
5) Students employed by projects - we are allowed to include PhD studentships on ESRC project grant applications; Research Assistants employed on grants can also register for part-time PhDs if the School agrees to waive their fees (the employment usually needs to be for at least three years).
6) Self funded students - these do occur, but students will need to pay registration fees; for example people in employment who want a PhD can enrol as part-time students.

To apply, students will have to complete an online application form that includes a **project proposal.** They should work on this with a prospective supervisor (i.e., you). Applications are shortlisted by a committee of senior academics in the School, and then candidates are invited for interview.

## School Research Groups

The school is not organised into formal groups, but staff create overlapping and dynamic groupings that everyone (including visitors, postgraduates, placement students, and often project students) is welcome to join. These usually meet every other week for a discussion group, and should maintain a Discourse post with a schedule of meetings so that everyone knows about them.

[Links to research groups](#research-groups)
