# Definitive Module Records (DMRs)

Definitive module records (DMRs) are the document used by the University Quality team to track module learning outcomes, assessments and other features.

They are the documents which are validated as part of a programme approval process.

Part A of the module record is therefore fixed, and to change it module leaders need to submit a request for minor changes to a module.

However Part B can (and should) be updated by module leaders each year to reflect new readings etc.


## Finding DMRs

You can find current versions of PSYC DMRs [here.](https://liveplymouthac.sharepoint.com/sites/u414/Programme%20Documentation/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fu414%2FProgramme%20Documentation%2FModule%20Records&FolderCTID=0x012000214FFBAF16A46F4A831ED01387C65C43&View=%7BD65535BD%2D0623%2D48EB%2D9A60%2D48ACF47AB01E%7D#InplviewHashd65535bd-0623-48eb-9a60-48acf47ab01e=Paged%3DTRUE-PagedPrev%3DTRUE-p_SortBehavior%3D0-p_FileLeafRef%3DPSY577%252e1%252edocx-p_ID%3D1257-PageFirstRow%3D871)from around file 880 onwards. 

These  are the documents which are validated as part of a programme approval process.



## Changing a DMR


Part A of the module record is therefore fixed, and to change it module leaders need to submit a request for minor changes to a module.

However Part B can (and should) be updated by module leaders each year to reflect new readings etc.


--- 
To change part A, module leaders need to submit a request for **minor changes** to a module using the forms below.


- [FoH minor Change form for 2024-25 Implementation updated March 2024.docx|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/FoH%20minor%20Change%20form%20for%202024-25%20Implementation%20updated%20March%202024.docx?d=w18e1905c61364fbf97b6df582fade488&csf=1&web=1&e=1MFjva)


In order to propose changes to programmes and/or modules for implementation, the form must be submitted along with a track-changed version of the module record. This form should be used for changes to Section A and/or B of module records. If the only change is to a Module/Programme lead please email [Health-Quality@plymouth.ac.uk](mailto:Health-Quality@plymouth.ac.uk) with the change.

The required documentation must be scrutinised by the following prior to submission to the relevant Associate Head Teaching and Learning (AHT&L):

* External Examiner (comment required from EE, unless changes are to Part B of the Module Record only)
* Programme Lead
* Members of the relevant Programme Committee

Following scrutiny, please submit the documentation to your AHT&L for sign off before sending into [Health-Quality@plymouth.ac.uk](mailto:Health-Quality@plymouth.ac.uk).

### Changes to assessment

If you are just making changes to the assessment that does not affect the weightings or number of components or elements (e.g., changing an exam from 4 to 3 questions, or into two sections; or changing the nature of a piece of coursework) then you do not need to submit a form.

If you want to split a coursework component into two pieces of work, or combine two pieces or make them 'either-or' then you DO need to submit a form.


### Larger changes

More substantial changes to modules should be documented in a request for major changes. 

* [Major Change form (as of Jan 2024 so check it's up to date)|attachment](https://liveplymouthac.sharepoint.com/:w:/r/sites/SchoolofPsychologyStaff/Shared%20Documents/General/sis/files/FoH%20Change%20to%20Module%20and-or%20Programme%20Lead%20Form%20(Updated%20Aug%202021).docx?d=wc323b9bf2a9b4b6a9b78ac73f98afbee&csf=1&web=1&e=AovkFm)

Contact the University quality team for the latest form (or [possibly find later ones here](https://liveplymouthac.sharepoint.com/sites/u414/SitePages/Site%20Home.aspx) )

Changes to multiple modules on a programme may trigger a revalidation of the programme. Check with the AHoS T&L.`Preformatted text`
