# Honorary and Visiting Staff

Please see the [HR community pages](https://liveplymouthac.sharepoint.com/sites/u114/SitePages/Recruitment.aspx) and [Honorary and Visiting Appointment Procedure.pdf](https://liveplymouthac.sharepoint.com/sites/u114/HR%20portal%20documents/Forms/AllItems.aspx?id=%2fsites%2fu114%2fHR+portal+documents%2fContracts%2fVisiting_Honorary_Volunteers%2fHonorary+and+Visiting+Appointment+Procedure.pdf&parent=%2fsites%2fu114%2fHR+portal+documents%2fContracts%2fVisiting_Honorary_Volunteers&xsdata=MDV8MDJ8am9uLm1heUBwbHltb3V0aC5hYy51a3xhNTA1YzMwNTBhM2Y0ODFhYzA3MjA4ZGM1ZGYwNjI4NXw1NDM3ZTdlYjgzZmI0ZDFhYmZkM2JiMjQ3ZTA2MWJmMXwxfDB8NjM4NDg4NTM0MzU4MzIwMzgxfFVua25vd258VFdGcGJHWnNiM2Q4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazFoYVd3aUxDSlhWQ0k2TW4wPXwwfHx8&sdata=eUlxNDNrQ1cxTWhxYkZFRWg5N3NnV3BKeTFIR1crSEFOdGd4dDZWU1BXYz0%3d)

**Honorary Process:**

When your faculty identifies an individual that you would like to invite to become an honorary, please arrange for them to apply for the honorary role via the recruitment requisition below;this allows easier tracking and provides us with all the onboarding information required. You will need to provide an instruction to the individual advising them which link to use as there are 8 requisitions set up for your area which align with current honorary engagements in your Faculty:

-   BMBS

-   Peninsula Dental School

-   School of Psychology

-   School of Nursing and Midwifery

-   Peninsula Medical School

-   School of Biomedical Sciences

-   School of Health Professions

Faculty of Health (*please use only when the role does not fall within a particular school*)

We need to ensure that we do not breach any data protection rules hence the individual requisitions. [Here is the link](https://hrservices.plymouth.ac.uk/tlive_webrecruitment/wrd/run/ETREC105GF.open?WVID=3337813Ucg)

Our team will arrange to forward applications received to the relevant areas on a weekly basis.

If the honorary engagement is approved, please complete the Honorary Workbook: [Honorary workbook.xlsx](https://liveplymouthac.sharepoint.com/sites/u114/HR%20portal%20documents/Recruitment/Honorary%20workbook.xlsx?web=1&xsdata=MDV8MDJ8am9uLm1heUBwbHltb3V0aC5hYy51a3xhNTA1YzMwNTBhM2Y0ODFhYzA3MjA4ZGM1ZGYwNjI4NXw1NDM3ZTdlYjgzZmI0ZDFhYmZkM2JiMjQ3ZTA2MWJmMXwxfDB8NjM4NDg4NTM0MzU4MzQ1MDcyfFVua25vd258VFdGcGJHWnNiM2Q4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazFoYVd3aUxDSlhWQ0k2TW4wPXwwfHx8&sdata=MFE5UFNxa2Y2dE5RS1hZK1psTE5CazdiTHpxd1dybEZvZFQrcnVSQU84TT0%3d) (Please use this link going forward and not a downloaded copy of the workbook to ensure that you are always using the very latest version).

Please see the last page of the Honorary and Visiting Appointment procedure policy above which incorporates a high level process flow as the Honorary Workbook will need to be authorised according to these levels. Once authorised and you have completed the relevant right to work check, please share all documentation with [vacancies\@plymouth.ac.uk](mailto:vacancies@plymouth.ac.uk)

Reporting: The End of Fixed Term process which was split in two, HUF’s and then all other titles, has now been combined. Faculties will now receive automatic notifications for all Honorary titles that are coming to an end on the 21st of the month going forward.

**Visiting Process:**

Any requests for new visitors carrying out academic teaching or research engagements will need to be submitted via the [Due Diligence process -Visiting Scholars](https://apply-ethicsonlinesystem.plymouth.ac.uk/)

Downloadable guidance notes are available on the [Help page:](https://apply-ethicsonlinesystem.plymouth.ac.uk/Personalisation/DisplayPage/9)

If the visitor request is approved, HR will send an engagement letter to the individual to confirm this with details of any documents required and instructions on how to register for an IT account. HR will also contact the Faculty Admin Office to advise them of the engagement and what documents they should expect to be presented with on the individual’s arrival to the UK, ie visa, flight details. As with all document checks, this check will need to be conducted prior to any engagement commencing with the University.

Reporting: A new automated End of Fixed Term process will trigger on the 29th of each month for British and Irish nationals. This automated email will be sent to the Line Manager with instructions to use the Due Diligence system if an extension is required. As many visitors arrive in the UK on specific visitor visas, the HR Team here will check any non UK nationals and separately pick these up with managers/faculty offices each month. We will automatically end engagements when the maximum duration of a visitor visa (12 months) has elapsed.

**Please contact Helen Garner, HR Contracts and Recruitment Manager, if you have any queries** – [hgarner\@plymouth.ac.uk](mailto:hgarner@plymouth.ac.uk)

Best wishes

Helen

**Helen Garner**

**Contracts and Recruitment Manager**

Human Resources, University of Plymouth, 17a Portland Villas, Drake Circus, Plymouth, PL4 8AA

[hgarner\@plymouth.ac.uk](mailto:hgarner@plymouth.ac.uk)

extension 88191
