name: Deploy R Markdown Site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        shell: Rscript {0}
        run: install.packages(c('rmarkdown', 'bookdown'), repos = 'https://cloud.r-project.org')

      - name: Build R Markdown site
        working-directory: docs
        shell: Rscript {0}
        run: bookdown::render_book("source/index.Rmd", encoding = "UTF-8")

      - name: Commit rendered site
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add docs/
          git commit -m "Rebuild site" || echo "No changes to commit"
          git push